name: CI

on:
  push:
    tags:
      - v0.**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          #platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: nostradamusai/nostradamus:${{ steps.get_version.outputs.VERSION }}
